INSERT INTO Category
	(CategoryName, Description, ImageURL)
VALUES 
	('PC Components', 'Everything you need to build, upgrade, or repair your PC — CPUs, GPUs, motherboards, RAM, storage, power supplies, and cooling, all in one place. Trusted brands, every budget, from first build to full custom rig.', 'https://images.rawpixel.com/image_social_landscape/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA1L2ZsMjI2MTMzNTM5MjUtaW1hZ2Uta3A0dzFscHAuanBn.jpg'),
    ('Gaming','Gear up for every playstyle — consoles, controllers, headsets, gaming chairs, and accessories built for performance and comfort. Whether youre competing or casually gaming, find the setup that keeps you in the action.','https://live.staticflickr.com/925/29448074488_f40ed3b9f9_z.jpg'),
    ('Monitors','From everyday displays to high-refresh gaming panels and ultrawide setups, find the right screen for work, creativity, or play. Crisp resolutions, fast response times, and sizes to fit any desk','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxJp5AokuziFtb7TjcC_RgvvLtH7WcLQee5DvccHNToCArrTyQT8T3gE2P&s=10'),
    ('Laptops','Portable power for work, study, or gaming on the go. Browse ultrabooks, business laptops, and high-performance gaming machines from brands you trust, with options to suit every budget and use case.','https://www.vernontechnology.com/wp-content/uploads/2022/10/vernon-best-laptops-for-graphic-designers-1024x685.jpg'),
    ('Mobile Accessories','Cases, chargers, screen protectors, power banks, and more — everything to protect, power, and personalize your phone or tablet. Practical extras that keep your devices ready for anything.','https://cdn2.picryl.com/photo/2013/03/15/electronic-devices-aid-the-enemy-184cfd-1024.jpg'),
    ('Audio','Headphones, earbuds, speakers, and soundbars for music, gaming, and calls. Immersive sound and reliable comfort, from everyday listening to studio-grade quality.','https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA1L3B4NzE0MDgzLWltYWdlLWt3dnhoOXg5LmpwZw.jpg'),
    ('Storage','Keep your files, games, and backups safe and accessible. Shop internal and external drives, SSDs, HDDs, and flash storage — fast, reliable capacity for any setup.','https://i1.pickpik.com/photos/919/189/178/computer-technology-pc-electronics-preview.jpg'),
    ('Networking','Stay connected with routers, modems, range extenders, and networking cables. Reliable, fast connections for streaming, gaming, working from home, or keeping a whole household online.','https://cdn12.picryl.com/photo/2016/12/31/network-cable-ethernet-computer-communication-c2c026-1024.jpg'),
    ('Cables & Adapters','The small essentials that keep everything connected — HDMI, USB-C, charging cables, and adapters for every device. Practical, affordable fixes for everyday connectivity needs.','https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg1NTM1ODctaW1hZ2Uta3d2eG9hc3MuanBn.jpg'),
    ('Power','Power supplies, surge protectors, extension cords, and battery backups to keep your devices running safely. Reliable protection and power for home, office, or gaming setups.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB02RSV86Hk2qJoV_IbYF6L1Ckch5YgUU9n85Fu9zNhSZ3KSAtJGx5_wg&s=10');