INSERT INTO Product
	(CategoryID, Name, Description, Brand, Price, StockQuantity, ImageURL)
VALUES
	('3','NACON Wired Controller for PlayStation PS4 and PC','OFFICIALLY LICENSED FOR PS4: Licensed by Sony for PlayStation 4 and compatible with PC. Featuring the official PlayStation 4 controller layout, including touch pad, SHARE and OPTIONS buttons, and LED player status indicator.','Nacon','1400.00','50','https://m.media-amazon.com/images/I/61St-7N14RL._AC_SX679_.jpg'),
    ('3','Microsoft Xbox Series X 1TB SSD Gaming Console, Black','Microsoft Xbox Series X is a powerful next-gen gaming console that offers a significant upgrade over its predecessors. Boasts a custom Zen 2 CPU and RDNA 2 GPU, delivering 12 teraflops of processing power for smooth gameplay and stunning visuals.','Microsoft','16999.99','2','https://m.media-amazon.com/images/I/41aowHBGaJL._AC_SX679_.jpg'),
    ('4','Lenovo Windows 11 Pro Laptop - Business Black','Elevate Your Computing Experience Equipped with Intel Core processor, the Lenovo V15 Gen 5 laptop tackles demanding applications and multitasking with ease. Dual memory slots mean fast loading times and no storage worries.','Lenovo','9899.99','121','https://m.media-amazon.com/images/I/71sn8ZVJIzL._AC_SY450_.jpg'),
    ('4','14" Student Laptop Intel','Empower your learning and productivity with the Student Laptop 14", a compact and powerful notebook designed for students, professionals, and everyday users.','Generic','4000.00','500','https://m.media-amazon.com/images/I/51vrp-1YA6L._AC_SY450_.jpg'),
    ('4','HP 255 15.6 inch G10 Notebook PC','The HP 255 G10 Laptop provides essential business-ready features in a thin and light design that’s easy to take everywhere you go.','HP','9299.99','500','https://m.media-amazon.com/images/I/41yMau0FmEL._AC_SX450_.jpg'),
    ('5','SAMSUNG GALAXY A06 64GB DS BLACK','The Galaxy A06 is a blend of style, functionality, and innovation. Featuring a stunning 6.7” TFT U-Cut Display, this smartphone offers an immersive visual experience with smooth 60Hz scrolling, perfect for streaming, gaming, or browsing.','Samsung','1772.50','125','https://m.media-amazon.com/images/I/71w9Ws0Oc+L._AC_SX679_.jpg'),
    ('5','Body Glove Astrx Case for Apple iPhone 15 Pro, Black','Body Glove Astrx Case is a high quality soft and ultra-thin case with a carbon fibre pattern. It protects your device against shock scratches and accidental drops.','Body Glove','119.00','400','https://m.media-amazon.com/images/I/513pOpdP6HL._AC_SX569_.jpg'),
    ('5','Apple iPhone 15 Pro Max FineWoven Case with MagSafe - Evergreen ​​​​​​​','Made from durable micro-twill, the material has a soft, suede-like feel. The FineWoven material was also designed with the earth in mind.','Apple','1899.99','5','https://m.media-amazon.com/images/I/51FZB8bN4JL._AC_SX679_.jpg'),
    ('10','MSI RTX 5060 Shadow 8G 2X OC Graphics Card','MSI RTX 5060 Shadow 8G 2X OC Graphics Card is built to deliver high-efficiency cooling, strong performance and whisper-quiet operation.','MSI','9225.50','12','https://m.media-amazon.com/images/I/51XJyS9z-pL._AC_SX450_.jpg');