CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    Role ENUM('Customer', 'Admin') NOT NULL DEFAULT 'Customer',
    DateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Category(
	CategoryID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL,
    Description VARCHAR(255) NOT NULL,
	ImageURL VARCHAR(255) NOT NULL
);

CREATE TABLE Product(
	ProductID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CategoryID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Brand VARCHAR(50) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL,
    ImageURL VARCHAR(255) NOT NULL,
    
    FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID)
);

CREATE TABLE Cart(
	CartID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
    DateCreated DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE CartItem(
	CartItemID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CartID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    
    FOREIGN KEY(CartID) REFERENCES Cart(CartID),
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE User_Order(
	OrderID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
    Order_Date DATE NOT NULL DEFAULT (CURRENT_DATE),
    Status VARCHAR(50) NOT NULL,
    TotalAmount DECIMAL(10, 2) NOT NULL,
    ShippingAddress VARCHAR(100) NOT NULL,
    
    FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE OrderItem(
	OrderItemID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10,2) NOT NULL,
    
    FOREIGN KEY(OrderID) REFERENCES User_Order(OrderID),
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE Wishlist(
	WishlistID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
	DateCreated DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE WishlistItem(
	WishlistItemID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ProductID INT NOT NULL,
    WishlistID INT NOT NULL,
    
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID),
    FOREIGN KEY(WishlistID) REFERENCES Wishlist(WishlistID)
);

CREATE TABLE CustomizationService(
	ServiceID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CategoryID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    ExtraCost DECIMAL(7,2) NOT NULL,
    
    FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID)
);

CREATE TABLE Payment(
	PaymentID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    OrderID INT NOT NULL,
    PaymentMethod VARCHAR(50) NOT NULL,
    PaymentStatus VARCHAR(50) NOT NULL,
    PaymentDate DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(OrderID) REFERENCES User_Order(OrderID)
);

CREATE TABLE Specification(
	SpecificationID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ProductID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Spec_Value VARCHAR(50) NOT NULL, 
    
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE Review(
	ReviewID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    Rating TINYINT NOT NULL CHECK(Rating BETWEEN 1 AND 10),
    Comment VARCHAR(255) NOT NULL,
    ReviewDate DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(UserID) REFERENCES User(UserID),
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
);