CREATE TABLE Cart(
	CartID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
    DateCreated DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(UserID) REFERENCES User(UserID)
);

SELECT * FROM Cart;

INSERT INTO Cart
	(UserID)
VALUES
	('1');