CREATE TABLE Wishlist(
	WishlistID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserID INT NOT NULL,
	DateCreated DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    FOREIGN KEY(UserID) REFERENCES User(UserID)
);

SELECT * FROM Wishlist;

INSERT INTO Wishlist
	(UserID)
VALUES
	('1');